Updates for comparison of v3.1 new samples to the v2 exomes using pc relate
broadinstitute/gnomad_qc pull request #211
Opened 2021-08-19 22:06 UTC by jkgoodrich

We realized that there are some samples new to v3.1 (not in v3) where the sample ID didn't match a v2 exome sample ID, but was a duplicate sample based on formal relatedness checks with pc_relate (as was done for the v3 genomes with the v2 exomes). 

This code updates the previous v2 exome/v3 gnome pc_relate code to only compare v3.1 new samples to v2 exomes.

2021-08-30 16:00 UTC, klaricch requested changes

2021-08-30 16:00 UTC, klaricch commented on gnomad_qc/v3/sample_qc/v2_pc_relate.py
> +    v2_v3_relatedness,
do imports have to be alphabetical as well?

2021-08-30 16:00 UTC, klaricch commented on gnomad_qc/v3/sample_qc/v2_pc_relate.py
> +    parser.add_argument('--filter_to_new_3_1_samples', help='Only run the join/PC_relate on v2 exomes combined with v3.1 new samples.', action='store_true')
above help statements don't have a period but this one does

2022-01-27 20:53 UTC, gtiao commented
Julia says this code is outdated but not worth spending the time to polish, but it may be useful to use as a model for writing code for v4 exomes to v3 genome comparison. Only Sanna has used this code.

2022-10-04 13:55 UTC, ch-kr commented
Closing this as it has been linked in another ticket

2022-10-04 13:55 UTC, closed without merging