V4 resources
broadinstitute/gnomad_qc pull request #218
Opened 2021-11-10 16:41 UTC by klaricch

2021-11-15 22:12 UTC, jkgoodrich requested changes
Thank you so much for putting this in Kristen!

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            for release in VERSIONS
```suggestion
            version: TableResource(
                _get_ancestry_pca_ht_path(
                    "loadings", version, include_unreleasable_samples
                )
            )
            for version in VERSIONS
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            for release in VERSIONS
```suggestion
            version: TableResource(
                _get_ancestry_pca_ht_path(
                    "scores", version, include_unreleasable_samples
                )
            )
            for version in VERSIONS
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            for release in VERSIONS
```suggestion
            version: TableResource(
                _get_ancestry_pca_ht_path(
                    "eigenvalues", version, include_unreleasable_samples
                )
            )
            for version in VERSIONS
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +        release: MatrixTableResource(
```suggestion
        version: MatrixTableResource(
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +        for release in VERSIONS
```suggestion
        for version in VERSIONS
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +        for release in VERSIONS
```suggestion
        version: TableResource(
            f"{get_sample_qc_root(version)}/gnomad_v{version}_pc_scores.ht"
        )
        for version in VERSIONS
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +        for release in VERSIONS
```suggestion
        version: TableResource(
           f"{get_sample_qc_root(version)}/gnomad_v{version}_relatedness.ht"
        )
        for version in VERSIONS
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +import hail as hl
Note: Part way through this file I stopped changing `release` to `version`, can you change them all?

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +# TODO: Should this still be a "temp" directory?
Good call, nope

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +    return f"gs://gnomad/v{version}/sample_qc/temp/exomes/gnomad_v{version}_RF_pop_assignments.txt.gz"
```suggestion
    return f"gs://gnomad/v{version}/sample_qc/exomes/gnomad_v{version}_RF_pop_assignments.txt.gz"
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +    return f"gs://gnomad/v{version}/sample_qc/temp/exomes/gnomad_v{version}_pop.RF_fit.pickle"
```suggestion
    return f"gs://gnomad/v{version}/sample_qc/exomes/gnomad_v{version}_pop.RF_fit.pickle"
```

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +# For v4 might not use this (regresed metrics used instead)
Yeah we might not use it, but we will probably still calculate it to look at

2021-11-15 22:12 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +# Picard metrics
We will probably change this to just have the picard metrics on the project metadata HT, so maybe move this to the meta.py resource file

2021-11-17 14:59 UTC, klaricch commented on gnomad_qc/v4/resources/constants.py
> +CURRENT_VERSION = "4.0"
i like 4.0 -- seems like a more consistent format with later versions when we increment

2021-11-30 14:56 UTC, jkgoodrich requested changes
Just some more changes for consistency, mostly changing to `.` instead of `_`

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_pc_scores.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.pc_scores.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_relatedness.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.relatedness.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_sex.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.sex.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_related_samples_to_drop_for_pca.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.related_samples_to_drop_for_pca.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_related_release_samples_to_drop.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.related_release_samples_to_drop.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_clinvar.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.clinvar.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +    return f"gs://gnomad/v{version}/sample_qc/exomes/gnomad_exomes_v{version}_pop.RF_fit.pickle"
```suggestion
    return f"gs://gnomad/v{version}/sample_qc/exomes/gnomad.exomes.v{version}.pop.RF_fit.pickle"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_hard_filtered_samples.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.hard_filtered_samples.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_stratified_metrics.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.stratified_metrics.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_regressed_metrics.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.regressed_metrics.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_pca_samples_ranking.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.pca_samples_ranking.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_release_samples_ranking.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.release_samples_ranking.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_exomes_v{version}_duplicates.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.exomes.v{version}.duplicates.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_v3_v{version}_release_pca_scores.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.v3_v{version}.release_pca_scores.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/sample_qc.py
> +            f"{get_sample_qc_root(version)}/gnomad_v3_v{version}_release_relatedness.ht"
```suggestion
            f"{get_sample_qc_root(version)}/gnomad.v3_v{version}.release_relatedness.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +                    f"{get_variant_qc_root(version)}/truth_samples/{truth_sample}.mt"
```suggestion
                    f"{get_variant_qc_root(version)}/truth_samples/gnomad.exomes.v{version}.{truth_sample}.mt"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +                    f"{get_variant_qc_root(version)}/truth_samples/{truth_sample}.ht"
```suggestion
                    f"{get_variant_qc_root(version)}/truth_samples/gnomad.exomes.v{version}.{truth_sample}.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +                f"{get_variant_qc_root(version)}/score_bins/{model_id}.{'aggregated' if aggregated else 'bins'}.ht"
```suggestion
                f"{get_variant_qc_root(version)}/score_bins/gnomad.exomes.v{version}.{model_id}.{'aggregated' if aggregated else 'bins'}.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +                f"{get_variant_qc_root(version)}/binned_concordance/{truth_sample}_{model_id}_binned_concordance.ht"
```suggestion
                f"{get_variant_qc_root(version)}/binned_concordance/gnomad.exomes.v{version}.{truth_sample}.{model_id}.binned_concordance.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +                f"{get_variant_qc_root(version)}/rf/rf_annotations.{'adj' if adj else 'raw'}.ht"
```suggestion
                f"{get_variant_qc_root(version)}/rf/gnomad.exomes.v{version}.rf_annotations.{'adj' if adj else 'raw'}.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +    return f"{get_variant_qc_root(version)}/rf/rf_runs.json"
```suggestion
    return f"{get_variant_qc_root(version)}/rf/gnomad.exomes.v{version}.rf_runs.json"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +    return f"{get_variant_qc_root(version)}/rf/models/{model_id}/rf.model"
```suggestion
    return f"{get_variant_qc_root(version)}/rf/models/{model_id}/gnomad.exomes.v{version}.rf.model"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +                f"{get_variant_qc_root(version)}/rf/models/{model_id}/training.ht"
```suggestion
                f"{get_variant_qc_root(version)}/rf/models/{model_id}/gnomad.exomes.v{version}.training.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +                f"{get_variant_qc_root(version)}/rf/models/{model_id}/rf_result.ht"
```suggestion
                f"{get_variant_qc_root(version)}/rf/models/{model_id}/gnomad.exomes.v{version}.rf_result.ht"
```

2021-11-30 14:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/variant_qc.py
> +            version: TableResource(f"{get_variant_qc_root(version)}/final_filter.ht")
```suggestion
            version: TableResource(f"{get_variant_qc_root(version)}/gnomad.exomes.v{version}.final_filter.ht")
```

2021-11-30 16:00 UTC, jkgoodrich commented
Not that it will have a ton in it yet, but lets add a README like we have for v2 and v3 and we should add to it as we add scripts

2021-12-08 16:48 UTC, jkgoodrich approved these changes
LGTM, thanks for moving that and fixing with the hl.vds.VariantDataset

2021-12-08 17:00 UTC, merged