Point to sample qc definitions in gnomad_meta
broadinstitute/gnomad_qc pull request #229
Opened 2022-02-17 13:59 UTC by mike-w-wilson

2022-02-18 21:12 UTC, jkgoodrich requested changes
OK, so after looking over the gnomad_meta PR, you were completely right Mike about splitting it up. I went ahead and did the split and then looked over the new additions. I had some extremely tiny things, but then this is good from my point of view, but can you take a look at the changes I made. Mostly make sure I did the split correctly, look at the first couple lines, and look at the `project_meta` annotation.

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +        * lower_cutoff_YY: Lower cutoff for double Y.
```suggestion
    * **x_ploidy_cutoffs**: Cutoffs for X ploidy.
        * **upper_cutoff_X**: Upper cutoff for single X.
        * **lower_cutoff_XX**: Lower cutoff for double X.
        * **upper_cutoff_XX**: Upper cutoff for double X.
        * **lower_cutoff_XXX**: Lower cutoff for triple X. 
    * **y_ploidy_cutoffs**: Cutoffs for Y ploidy.
        * **lower_cutoff_Y**: Lower cutoff for single Y.
        * **upper_cutoff_Y**: Upper cutoff for single Y.
        * **lower_cutoff_YY**: Lower cutoff for double Y.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +    * contamination: Whether the sample was flagged for contamination.
```suggestion
    * **contamination**: Whether the sample was flagged for contamination.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +    * relationships: Samples that have a kinship estimate (kin) > 0.05 determined using Hail’s [pc_relate](https://hail.is/docs/0.2/methods/relatedness.html#hail.methods.pc_relate) with this sample.
```suggestion
    * **relationships**: Samples that have a kinship estimate (kin) > 0.05 determined using Hail’s [pc_relate](https://hail.is/docs/0.2/methods/relatedness.html#hail.methods.pc_relate) with this sample.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +        * **n_snp**: SNP regression statistics
```suggestion
        * **n_snp**: SNP regression statistics.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +        * **r_ti_tv**: Transition/Transversion ratio regression statistics
```suggestion
        * **r_ti_tv**: Transition/Transversion ratio regression statistics.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +        * **n_insertion**: Insertion regression statistics
```suggestion
        * **n_insertion**: Insertion regression statistics.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +        * **n_deletion**: Deletion regression statistics
```suggestion
        * **n_deletion**: Deletion regression statistics.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +        * **r_het_hom_var**: Het/HomVar regression statistics
```suggestion
        * **r_het_hom_var**: Het/HomVar regression statistics.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +        * **n_transition**: Transition regression statistics
```suggestion
        * **n_transition**: Transition regression statistics.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +        * **n_tranversion**: Transversion regression statistics
```suggestion
        * **n_tranversion**: Transversion regression statistics.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +* **subsets**: Subsets of the gnomAD release HT that the sample belongs to
```suggestion
* **subsets**: Subsets of the gnomAD release HT that the sample belongs to.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +    * **non_topmed**: Whether the sample was included in the ‘non_topmed’ subset. Subset contains variants from samples that are not the TOPMED cohort. Generated using the negation of the ‘project_me
```suggestion
    * **non_topmed**: Whether the sample was included in the ‘non_topmed’ subset. Subset contains variants from samples that are not the TOPMED cohort. Generated using the negation of the ‘project_meta.topmed’ annotation.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +    * **controls_and_biobanks**: Whether the sample was included in the ‘controls_and_biobanks’ subset. Subset contains variants from samples that are either a control or from a biobank project. Gene
```suggestion
    * **controls_and_biobanks**: Whether the sample was included in the ‘controls_and_biobanks’ subset. Subset contains variants from samples that are either a control or from a biobank project. Generated matching on ‘case_control’ annotation values of ‘control' or 'biobank'.
```

2022-02-18 21:12 UTC, jkgoodrich commented on gnomad_qc/v3/sample_qc/README.md
> +* **high_quality**: Whether the sample is considered high quality (no hard filter or qc_metric filter flags)
```suggestion
* **high_quality**: Whether the sample is considered high quality (no hard filter or qc_metric filter flags).
```

2022-02-22 20:57 UTC, mike-w-wilson commented on gnomad_qc/v3/sample_qc/README.md
> +* **project_meta**: Metadata collected from collaborators or previous versions of gnomAD. The description of annotations in this struct can be found in the [gnomad_meta repo](https://github.com/broad
```suggestion
* **project_meta**: Metadata collected from collaborators or previous versions of gnomAD. The description of annotations in this struct can be found in the [gnomad_meta repo](https://github.com/broadinstitute/gnomad_meta/blob/master/v3.1/README.md) (for internal use only).
```

2022-02-22 21:10 UTC, mike-w-wilson reviewed
Looks like a few links got duplicated and its preventing the hyperlink from working properly so I just deleted the extra one.

2022-02-22 21:10 UTC, mike-w-wilson commented on gnomad_qc/v3/sample_qc/README.md
> +    * **n_pcs**: The number of principal components (PCs) used in [PC-project]([https://github.com/broadinstitute/gnomad_methods/blob/0b660daf23854efa5f6baa233ecbedce40d06fd3/gnomad/sample_qc/ancestr
```suggestion
    * **n_pcs**: The number of principal components (PCs) used in [PC-project](https://github.com/broadinstitute/gnomad_methods/blob/b95578056f8051d00dcbb749a10e585d48888f82/gnomad/sample_qc/ancestry.py#L80).
```

2022-02-22 21:10 UTC, mike-w-wilson commented on gnomad_qc/v3/sample_qc/README.md
> +* **relatedness_inference_cutoffs**: Contains relatedness inference cutoffs used when running Hail's [pc-relate]([https://hail.is/docs/0.2/methods/relatedness.html#hail.methods.pc_relate](https://hai
```suggestion
* **relatedness_inference_cutoffs**: Contains relatedness inference cutoffs used when running Hail's [pc-relate](https://hail.is/docs/0.2/methods/relatedness.html#hail.methods.pc_relate).
```

2022-02-22 21:10 UTC, mike-w-wilson commented on gnomad_qc/v3/sample_qc/README.md
> +* **qc_metrics_filters**: Set of all sample QC metrics for which each sample was found to be an outlier after computing sample QC metrics using Hail’s [sample_qc]([https://hail.is/docs/0.2/methods/ge
```suggestion
* **qc_metrics_filters**: Set of all sample QC metrics for which each sample was found to be an outlier after computing sample QC metrics using Hail’s [sample_qc](https://hail.is/docs/0.2/methods/genetics.html#hail.methods.sample_qc) and regressing out the first 8 ancestry assignment PCs.
```

2022-02-22 21:25 UTC, merged