Add code for v4 platform inference and platform inference tests
broadinstitute/gnomad_qc pull request #232
Opened 2022-02-26 18:03 UTC by jkgoodrich

2022-03-04 20:15 UTC, klaricch requested changes
looks good, just a few small things

2022-03-04 20:15 UTC, klaricch commented on gnomad_qc/v4/sample_qc/platform_inference.py
> +                        f"Please run --compute_coverage and -- run_platform_pca with the --test argument and needed "
```suggestion
                        f"Please run --compute_coverage and --run_platform_pca with the --test argument and needed "
```

2022-03-07 20:56 UTC, jkgoodrich commented on gnomad_qc/v4/resources/basics.py
> +    elif interval_name == "intersection":
Sounds good, will change

2022-03-07 20:56 UTC, jkgoodrich commented on gnomad_qc/v4/sample_qc/platform_inference.py
> +                args.calling_interval_padding,
yup, thank you, I will change

2022-03-07 20:56 UTC, jkgoodrich commented on gnomad_qc/v4/sample_qc/platform_inference.py
> +    parser.add_argument(
thank you, still in the previous mindset, will change

2022-03-07 21:38 UTC, jkgoodrich commented
Sorry, not positive about this pylint error yet

```
gnomad_qc/v2/annotations/generate_ld_data.py:184:13: E1101: Class 'BlockMatrix' has no '_from_java' member (no-member)
```

2022-03-08 16:40 UTC, klaricch approved these changes
LGTM!

2022-03-08 17:16 UTC, merged