Add script to generate hard filtered samples
broadinstitute/gnomad_qc pull request #237
Opened 2022-03-31 18:59 UTC by mike-w-wilson

This script adds hard filtering. I left what I considered to be TODOs commented in the code, e.g. determine threshold cut offs through visual inspection. I've tested this code on the test VDS so all samples are failing given the small number of variants.

This also adds a failed fingerprinting table resource.

2022-05-04 23:48 UTC, jkgoodrich commented
There are still some TODOs on this PR because I'm not sure what sample QC hard filters we will actually use. I think it's overkill to add min and max options for all possible sample QC metrics, and I would like to see the full gnomAD v4 sample QC metric distributions. This file will need to change after we determine the best hard filtering for gnomAD v4

2022-05-05 19:34 UTC, jkgoodrich commented
@klaricch will first look over just the sample QQ generation

2022-05-06 17:16 UTC, klaricch commented
> One question is, should the sex imputation addition just be its own argument that makes the final file, with an intermediate file made without it rather than an option that determines what is in the final file?

I think I like the former. How would that option for the latter be structured?

2022-05-06 17:17 UTC, klaricch requested changes

2022-05-09 17:25 UTC, jkgoodrich commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +def compute_sample_qc(n_partitions: int = 1000, test: bool = False) -> hl.Table:
arbitrary. I was going for a round number and trying to make it more partitions given the change in sample size from v3. It was 100 for the genomes in v3 which was ~150,000 samples (prior to releasable filtering) so maybe 500 would be better?

2022-05-09 17:29 UTC, jkgoodrich commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +            if args.test:
no, but I think you are right, it using multiple times, let's just define at the top and use the variable

2022-05-09 17:30 UTC, jkgoodrich commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +        help="Overwrite all data from this subset (default: False)",
Good catch, just a copy paste error

2022-05-09 17:31 UTC, jkgoodrich commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +        "--include-low-cov-filter",
No, I ended up removing it, I didn't think it was needed. I will remove the flag too. Thanks!

2022-05-09 17:34 UTC, jkgoodrich commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +        help="Filtering threshold to use for the minimum number of SNPs. Default is 2.4e6.",
it's the minimum cutoff though for `n_snp`, the maximum cutoff argument is above

2022-05-09 18:26 UTC, jkgoodrich commented
> > One question is, should the sex imputation addition just be its own argument that makes the final file, with an intermediate file made without it rather than an option that determines what is in the final file?
> 
> I think I like the former. How would that option for the latter be structured?

As is it will always write using

```
    .write(
                get_checkpoint_path(
                    f"test_gnomad.exomes.hard_filtered_samples.ht"
                )
                if test
                else hard_filtered_samples.path,
                overwrite=args.overwrite,
            )
```

No matter what the value of `args.include_sex_filter` is. But I'm wondering if instead we should include that in the name of the file if it's not set?

2022-05-09 20:29 UTC, klaricch requested changes

2022-05-09 20:29 UTC, klaricch commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +                    f"test_gnomad.exomes.hard_filtered_samples.ht"
```suggestion
                    "test_gnomad.exomes.hard_filtered_samples"
```

2022-05-09 20:29 UTC, klaricch commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +        help="Filtering threshold to use for the minimum number of SNPs. Default is 2.4e6.",
oops, meant to edit the arg above

2022-05-09 20:29 UTC, klaricch commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +def compute_sample_qc(n_partitions: int = 1000, test: bool = False) -> hl.Table:
500 sounds good

2022-05-16 16:39 UTC, jkgoodrich commented on gnomad_qc/v4/sample_qc/hard_filters.py
> +        help="Filtering threshold to use for the minimum number of SNPs. Default is 2.4e6.",
actually, I will just change all of those below to say maximum

2022-05-19 20:19 UTC, klaricch approved these changes
lgtm!

2022-05-19 20:28 UTC, merged