Changes needed during compute info runtime
broadinstitute/gnomad_qc pull request #417
Opened 2023-09-08 17:00 UTC by jkgoodrich

Also fixes issue of adj annotation for trio stats and changes annotation HT to allow for easy comparison of info methods

2023-09-11 05:20 UTC, jkgoodrich commented on gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
> +            m_info_ht = median_impute_features(
oops, I forgot to actually annotate ht with the imputed values...will add tomorrow

2023-09-12 15:24 UTC, klaricch requested changes

2023-09-12 16:10 UTC, jkgoodrich commented on gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
> +            **AS_INFO_AGG_FIELDS,
it's actually 4 arguments being passed, and this shows that it's all the defaults in gnomad_methods https://github.com/broadinstitute/gnomad_methods/blob/77d2be9a75fd74c0fbffafa7086fb4de5a688203/gnomad/utils/sparse_mt.py#L32

AS_INFO_AGG_FIELDS = {
    "sum_agg_fields": ["AS_QUALapprox", "AS_RAW_MQ"],
    "int32_sum_agg_fields": ["AS_VarDP"],
    "median_agg_fields": ["AS_RAW_ReadPosRankSum", "AS_RAW_MQRankSum"],
    "array_sum_agg_fields": ["AS_SB_TABLE"],
}

If it's OK with you I will keep as is, but I can add a comment if you think that would help

2023-09-12 16:17 UTC, klaricch commented on gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
> +            **AS_INFO_AGG_FIELDS,
ah that makes sense, yeah a comment would help

2023-09-12 17:08 UTC, klaricch approved these changes
lgtm

2023-09-12 17:12 UTC, merged