Add gen_anc_faf_max
broadinstitute/gnomad_qc pull request #456
Opened 2023-10-05 19:35 UTC by mike-w-wilson

This adds in the genetic ancestry group with the highest FAF per threshold and its value. This is different than grpmax which grabs the genetic ancestry group with the highest AF, and then also annotates its FAF. Highest AF does not equal highest FAF.

2023-10-05 20:36 UTC, KoalaQin requested changes

2023-10-05 20:36 UTC, KoalaQin commented on gnomad_qc/v4/annotations/generate_freq.py
> +    logger.info("Annotating 'faf','grpmax', and 'gen_anc_faf_max'...")
```suggestion
    logger.info("Annotating 'faf', 'grpmax', and 'gen_anc_faf_max'...")
```

2023-10-05 20:43 UTC, KoalaQin requested changes
I couldn't suggest changes at your docstring, could you modify it?

2023-10-05 20:43 UTC, KoalaQin commented on gnomad_qc/v4/annotations/generate_freq.py
>      for dataset, (freq, meta) in freq_metas.items():
You need to change the docstring above to include this too

2023-10-05 21:00 UTC, KoalaQin requested changes

2023-10-05 21:00 UTC, KoalaQin commented on gnomad_qc/v4/annotations/generate_freq.py
> +    :return: Hail Table with 'faf', 'grpmax', and 'gen_anc_faf_max' annotations.
How about L817?

2023-10-05 21:40 UTC, KoalaQin approved these changes
LGTM!

2023-10-06 16:25 UTC, jkgoodrich approved these changes
LGTM!

2023-10-06 16:45 UTC, merged