Add v4 genomes variant QC finalize script
broadinstitute/gnomad_qc pull request #483
Opened 2023-10-13 20:59 UTC by jkgoodrich

2023-10-15 14:56 UTC, KoalaQin requested changes

2023-10-16 04:36 UTC, jkgoodrich commented on gnomad_qc/v4/variant_qc/final_filter_genomes.py
> +from gnomad_qc.v4.resources.annotations import get_freq, get_info
oops, yup. Thank you for catching!

2023-10-16 19:08 UTC, KoalaQin commented
LGTM! The test run worked well!

2023-10-16 19:14 UTC, KoalaQin requested changes

2023-10-16 19:16 UTC, KoalaQin approved these changes
lgtm!

2023-10-16 19:37 UTC, merged