Validity check v4 exomes
broadinstitute/gnomad_qc pull request #487
Opened 2023-10-15 17:02 UTC by mike-w-wilson

This unfurls and runs gnomad_methods validate_release_t on the v4 exomes release HT. It depends on https://github.com/broadinstitute/gnomad_methods/pull/625 and there is some room for improvements but I just wanted to get it in. It writes out the HT with unfurled annotations that will move to the next step.

2023-10-16 13:15 UTC, mike-w-wilson commented
Loggers seem to not be working for me right now

2023-10-16 15:09 UTC, mike-w-wilson commented
Loggers are a gnomad_methods issue: https://the-tgg.slack.com/archives/C6BD1M01E/p1697463923095569

2023-10-18 16:47 UTC, jkgoodrich requested changes
I think this is looking good, I only looked at it for logic, which is totally fine at this point.


I think we might want to add in some other checks, like a check for length of globals being the expected length, and maybe counts being the expected counts. Maybe check for any uses of 'pop' or 'oth' in the globals?

Are there any other checks that we thing should be done on the globals? @ch-kr ?

Then only a few small suggestions

2023-10-18 16:47 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +                monoallelic_expr=ht.info.monoallelic,
Also add ht.info.only_het?

2023-10-18 16:47 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +                problematic_regions=["lcr", "segdup", "non_par"],
Should probably also look at the other region flags 
```
        fail_interval_qc: bool, 
        outside_ukb_capture_region: bool, 
        outside_broad_capture_region: bool
```

2023-10-18 16:47 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +            ht.write(res.validated_ht.path, overwrite=True)
Checkpoint the prepared HT before running the validity checks?

2023-10-18 16:47 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +            f"{field}" if field != "nonpar" else "non_par"
Is this still needed, it looks like you changed it in `REGION_FLAG_FIELDS`

2023-10-18 16:47 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +MISSING_ALLELE_TYPE_FIELDS = ["original_alleles", "has_star"]
has_star is in the exomes

2023-10-18 16:47 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +    "singleton",  # NOTE: doesn't look like it was exported to VCF in V3.1 and is not part of gnomad_methods vcf module so maybe we drop it? Easy enough to look at AC?
Works for me

2023-10-18 23:25 UTC, mike-w-wilson commented
I've updated this and it depends on https://github.com/broadinstitute/gnomad_methods/pull/630. In the `prepare_ht_for_validation` we select a subset of fields needed for VCF export and this gets checkpointed. I didnt want to add the freqs and fafs to this since they are so massive and are not needed downstream. For this reason, I put the global checks before that instead of calling it in gnomad methods validate_release_t.

2023-10-18 23:26 UTC, mike-w-wilson commented
Back to you @jkgoodrich !

Test here: https://console.cloud.google.com/dataproc/jobs/4e803d67e7d04016a560a9c4bf069907/monitoring?region=us-central1&project=broad-mpg-gnomad

2023-10-19 04:58 UTC, jkgoodrich requested changes
Only very small changes. I love seeing the output from the new checks, thank you so much for adding!!

2023-10-19 04:58 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +    "transmitted_singleton",
add sibling singletons

2023-10-19 04:58 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +# TODO: Check global lengths match the fields they reference
```suggestion
```

2023-10-19 04:58 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +        },  # release_sites().ht()},
I know this is just for testing, but don't forget to change it back

2023-10-19 04:58 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_exome_vcf.py
> +def check_globals_for_retired_terms(ht: hl.Table) -> None:
This is great, thank you!!

2023-10-19 16:41 UTC, jkgoodrich requested changes
two small things then lgtm

2023-10-19 16:41 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_vcf.py
> +        input_resources={"release_ht": release_sites().ht()},
```suggestion
        input_resources={"create_release_sites_ht.py": {"release_ht": release_sites()}},
```

2023-10-19 16:41 UTC, jkgoodrich commented on gnomad_qc/v4/create_release/validate_and_export_vcf.py
> +            ht = res.release_ht
```suggestion
            ht = res.release_ht.ht()
```

2023-10-19 16:58 UTC, jkgoodrich approved these changes
LGTM

2023-10-19 17:03 UTC, merged