Add option to remove extreme multiallelic in VDS
broadinstitute/gnomad_qc pull request #580
Opened 2024-03-12 13:56 UTC by KoalaQin

This adds in an option to delete an excessively multi-allelic locus on chr19 as we did in https://github.com/broadinstitute/gnomad_qc/blob/cdc3dd5b8cd3cf5e381addac96cd921d7fe604e8/gnomad_qc/v4/annotations/generate_freq.py#L258.

2024-03-15 22:29 UTC, jkgoodrich requested changes

2024-03-15 22:29 UTC, jkgoodrich commented on gnomad_qc/v4/resources/basics.py
> +        if remove_extreme_multi_allelic:
Let's just remove it no matter what, even if split is not True. Maybe switch to use filter_intervals with keep = False

2024-03-16 02:14 UTC, KoalaQin commented
Code to test if this was done: 
```
"""Test script for gnomAD v4 data"""
import hail as hl
from gnomad_qc.v4.resources.basics import get_gnomad_v4_vds

vds = get_gnomad_v4_vds()
vds = hl.vds.filter_intervals(
    vds,
    [hl.parse_locus_interval("chr19:5787204-5787205", reference_genome="GRCh38")],
)
print(vds.variant_data.count())
```
[ec223c63fde5413a93e1dfc7ca33e2c2](https://console.cloud.google.com/dataproc/jobs/ec223c63fde5413a93e1dfc7ca33e2c2?region=us-central1&project=broad-mpg-gnomad) output: 
(0, 940583)

2024-03-18 16:23 UTC, jkgoodrich approved these changes
LGTM!

2024-03-18 18:12 UTC, merged