Add sex, freq_index_dict and faf_index_dict in joint release HT
broadinstitute/gnomad_qc pull request #592
Opened 2024-04-01 20:49 UTC by KoalaQin

Changes:
1. Include "sex" in exomes and genomes faf; 
2. Add `freq_index_dict` and `faf_index_dict` in exomes and genomes globals; 
3. Fix failures on CMH test for testing (this change not working yet with Hail 0.2.128); 
4. Exclude pooled odds ratio from the stats; 

Now the joint HT is like this for faf meta: 
![Screenshot 2024-04-01 at 4 48 51 PM](https://github.com/broadinstitute/gnomad_qc/assets/44242118/08d30159-52e0-47b6-9ff0-ab06a6e0ce22)

2024-04-04 13:33 UTC, jkgoodrich requested changes

2024-04-04 15:38 UTC, KoalaQin commented on gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
>      faf_meta, faf = filter_arrays_by_meta(
Not really, we still have subset for ukb in exomes.

2024-04-04 15:40 UTC, KoalaQin commented on gnomad_qc/v4/create_release/create_combined_faf_release_ht.py
>      faf_meta, faf = filter_arrays_by_meta(
But maybe we don't need to filter to 'adj', because both were already filtered to adj.

2024-04-05 15:24 UTC, jkgoodrich approved these changes
LGTM!

2024-04-05 15:57 UTC, merged