Add options to filter to releasable trios only
broadinstitute/gnomad_qc pull request #638
Opened 2024-09-25 15:30 UTC by KoalaQin

Update the `run_generate_trio_stats` function to filter the fam_ht to releasable trios (pat-mat-proband) only. It won't overwrite the existing output for all trios.

2024-10-15 16:13 UTC, klaricch requested changes

2024-10-15 16:13 UTC, klaricch commented on gnomad_qc/v4/annotations/generate_variant_qc_annotations.py
> +        meta = vmt.cols()
could add a logger stating that filtering to releasable trios here

2024-10-16 12:45 UTC, KoalaQin commented
Back to you @klaricch!

2024-10-16 18:19 UTC, klaricch approved these changes
lgtm

2024-10-16 18:45 UTC, merged